name: 'Install DuckDB'
description: 'Install DuckDB library and headers for building extensions'
runs:
  using: 'composite'
  steps:
    - name: Install DuckDB (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # Build DuckDB from source to ensure ABI compatibility
        git clone --depth 1 --branch v1.1.3 https://github.com/duckdb/duckdb.git /tmp/duckdb-src
        cd /tmp/duckdb-src
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_UNITTESTS=0 -DBUILD_SHELL=0 ..
        make -j$(nproc) duckdb
        sudo cp src/libduckdb.so /usr/local/lib/
        sudo cp ../src/include/duckdb.h /usr/local/include/
        sudo cp ../src/include/duckdb.hpp /usr/local/include/
        sudo cp -r ../src/include/duckdb /usr/local/include/
        sudo ldconfig
        cd ~ && rm -rf /tmp/duckdb-src

    - name: Install DuckDB (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        wget -q https://github.com/duckdb/duckdb/releases/download/v1.1.3/libduckdb-osx-universal.zip
        unzip -q libduckdb-osx-universal.zip -d /tmp/duckdb
        sudo cp /tmp/duckdb/duckdb.h /usr/local/include/
        sudo cp /tmp/duckdb/duckdb.hpp /usr/local/include/
        sudo cp /tmp/duckdb/libduckdb.dylib /usr/local/lib/
        rm libduckdb-osx-universal.zip

    - name: Install DuckDB (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/duckdb/duckdb/releases/download/v1.1.3/libduckdb-windows-amd64.zip" -OutFile "libduckdb-windows-amd64.zip"
        Expand-Archive -Path "libduckdb-windows-amd64.zip" -DestinationPath "C:\duckdb"
        Copy-Item "C:\duckdb\duckdb.h" -Destination "C:\Program Files\duckdb\include\" -Force
        Copy-Item "C:\duckdb\duckdb.hpp" -Destination "C:\Program Files\duckdb\include\" -Force
        Copy-Item "C:\duckdb\duckdb.dll" -Destination "C:\Program Files\duckdb\lib\" -Force
        Copy-Item "C:\duckdb\duckdb.lib" -Destination "C:\Program Files\duckdb\lib\" -Force
        Remove-Item "libduckdb-windows-amd64.zip"
        echo "CMAKE_PREFIX_PATH=C:\Program Files\duckdb" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
