name: Deploy Extensions

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Workflow run ID to download artifacts from (leave empty to use latest)'
        required: false
        type: string
  workflow_call:

jobs:
  deploy-extensions:
    runs-on: self-hosted
    permissions:
      packages: write
    steps:
      - name: Free disk space on Ubuntu runner
        uses: kfir4444/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      
      - uses: actions/checkout@v4

      - name: Restructure directories
        run: |
          mv scripts/extension ../extension-scripts
          rm -rf *
          mv ../extension-scripts/* .

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ryu-extensions
          run-id: ${{ inputs.run_id || github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure dataset directory exists
        run: |
          mkdir -p dataset
          if [ ! "$(ls -A dataset)" ]; then
            echo "Dataset directory is empty, creating placeholder"
            echo "# Dataset placeholder" > dataset/README.md
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/ryugraph/extension-repo:latest
