name: Build Windows Java Lib

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-windows-java:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: ./scripts

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build Java lib for Windows
        shell: cmd
        run: |
          make java NUM_THREADS=48

      - uses: actions/upload-artifact@v4
        with:
          name: java-lib-win-x86_64
          path: tools/java_api/build/libryu_java_native*
