name: Build Windows Node.js Module

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false
        
jobs:
  build-windows-nodejs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: ./scripts

      - name: Install Node.js dependencies
        working-directory: tools/nodejs_api
        run: |
          npm i

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build Node.js native module
        shell: cmd
        run: |
          make nodejs NUM_THREADS=48

      - name: Move Node.js native module
        working-directory: tools/nodejs_api/build
        run: ren ryujs.node ryujs-win32-x64.node

      - uses: actions/upload-artifact@v4
        with:
          name: windows-nodejs-module
          path: tools/nodejs_api/build/ryujs-win32-x64.node
